[project]
name = ""
version = ""
description = ""
authors = [
    {name = "Yifen", email = "112701002@nccu.edu.tw"},
]
dependencies = [
    "flask>=3.0.0",
]
requires-python = ">=3.8"
readme = "README.md"
license = {text = "MIT"}

